accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('update/', views.update, name='update'),
    path('<str:username>/', views.profile, name='profile'),
]

info/urls.py
from django.urls import path
from .views import contact_view, about_view, policy_view

urlpatterns = [
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('policy/', policy_view, name='policy'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404
from accounts.views import custom_404
from django.conf import settings
from django.conf.urls.static import static

handler404 = custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls')),
    path('', include('payment.urls')),
    path('', include('info.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    ACTIVE = 'active'
    NOT_ACTIVE = 'not_active'

    RESELLER_STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (NOT_ACTIVE, 'Not Active'),
    ]

    name = models.CharField(max_length=255)
    shopname = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=11)
    address = models.TextField()
    email_verified = models.BooleanField(default=False)
    reseller_status = models.CharField(
        max_length=10,
        choices=RESELLER_STATUS_CHOICES,
        default=NOT_ACTIVE
    )
    activation_date = models.DateTimeField(null=True, blank=True)
    expiry_date = models.DateTimeField(null=True, blank=True)

class ActivationRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11)
    reference = models.CharField(max_length=255, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    trxid = models.CharField(max_length=255)
    requested_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Activation request by {self.user.username}"
    

shop/models.py
from django.db import models
from django.conf import settings
from .utils import upload_image_to_imgbb
from django.utils import timezone
from django.utils.text import slugify
from tinymce.models import HTMLField

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    cateImage = models.ImageField(upload_to='cate_img/', blank=True, null=True, verbose_name='Category Image')
    imgbb_url = models.URLField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        
        super().save(*args, **kwargs)
        
        if self.cateImage and not self.imgbb_url:
            imgbb_url = upload_image_to_imgbb(self.cateImage.path, settings.IMGBB_API_KEY)
            if imgbb_url:
                self.imgbb_url = imgbb_url
                super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    description = HTMLField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        
        super().save(*args, **kwargs)

    def __str__(self):
        # return f"Product : {self.name}"
        return ''

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_img/', blank=True, null=True)
    imgbb_url = models.URLField(blank=True, null=True)
    def save(self, *args, **kwargs):
        if self.image:  # Only proceed if an image is provided
            super().save(*args, **kwargs)  # Save the model instance first to generate the ID
            imgbb_url = upload_image_to_imgbb(self.image.path, settings.IMGBB_API_KEY)
            if imgbb_url:
                self.imgbb_url = imgbb_url
                super().save(*args, **kwargs)  # Save the model instance again to update imgbb_url
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return f"Image : {self.product.name}"

class Banner(models.Model):
    banner = models.ImageField(upload_to='banner_img/', blank=True, null=True)
    imgbb_url = models.URLField(blank=True, null=True)
    def save(self, *args, **kwargs):
        if self.banner:  # Only proceed if an image is provided
            super().save(*args, **kwargs)  # Save the model instance first to generate the ID
            imgbb_url = upload_image_to_imgbb(self.banner.path, settings.IMGBB_API_KEY)
            if imgbb_url:
                self.imgbb_url = imgbb_url
                super().save(*args, **kwargs)  # Save the model instance again to update imgbb_url
        else:
            super().save(*args, **kwargs)

class Order(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.TextField()

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Reseller")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255)
    product_price = models.DecimalField(max_digits=10, decimal_places=0)

    profit = models.PositiveIntegerField(default=0)
    sell_price = models.DecimalField(max_digits=10, decimal_places=0)
    delivery_charge = models.DecimalField(max_digits=10, decimal_places=0, default=120)
    adv = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Advance")
    cod = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Cash on Delivery")
    quantity = models.PositiveIntegerField(default=1)

    trxid = models.CharField(max_length=100, verbose_name="TrxID")
    bKash = models.CharField(max_length=20, default='0')
    amount = models.DecimalField(max_digits=10, decimal_places=0, default='0')
    reference = models.CharField(max_length=255, default='0')

    invoice_no = models.CharField(max_length=100, unique=True)
    invoice_date = models.DateTimeField(default=timezone.now)

    PROFIT_STATUS_CHOICES = [
        ('PAID', 'Paid'),
        ('UNPAID', 'Unpaid'),
    ]
    
    profit_status = models.CharField(
        max_length=15,
        choices=PROFIT_STATUS_CHOICES,
        default='UNPAID',
    )
    
    ORDER_STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('CONFIRMED', 'Confirmed'),
    ]
    
    order_status = models.CharField(
        max_length=15,
        choices=ORDER_STATUS_CHOICES,
        default='PENDING',
    )

    DELIVERY_STATUS_CHOICES = [
        ('PROCESSING', 'Processing'),
        ('DELIVERED', 'Deliverd'),
        ('RETURNED', 'Returned'),
    ]
    
    delivery_status = models.CharField(
        max_length=15,
        choices=DELIVERY_STATUS_CHOICES,
        default='PROCESSING',
    )

    def __str__(self):
        return self.invoice_no

accounts/views.py
import random, string
from accounts.models import ActivationRequest
from shop.models import Order
from django.db.models import Sum
from django.utils import timezone
from django.contrib import messages
from django.core.mail import EmailMessage
from payment.models import RequestedPayment
from django.core.exceptions import ValidationError

from django.conf import settings
from django.core.validators import validate_email

from django.contrib.auth import get_user_model
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect, get_object_or_404

User = get_user_model()

@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    
    if request.user != user and not request.user.is_staff:
        return redirect('home')
    
    delivered_orders = Order.objects.filter(user=user, delivery_status='DELIVERED')
    paid_orders = delivered_orders.filter(profit_status='PAID')
    unpaid_orders = delivered_orders.filter(profit_status='UNPAID')
    
    total_sell = delivered_orders.aggregate(total_sell=Sum('sell_price'))['total_sell'] or 0
    total_profit = delivered_orders.aggregate(total_profit=Sum('profit'))['total_profit'] or 0
    paid_profit = paid_orders.aggregate(paid_profit=Sum('profit'))['paid_profit'] or 0
    unpaid_profit = unpaid_orders.aggregate(unpaid_profit=Sum('profit'))['unpaid_profit'] or 0
    
    orders = Order.objects.filter(user=user).order_by('-invoice_date')
    
    today = timezone.now().date()
    can_request_payment = 1 <= today.day <= 7 and not RequestedPayment.objects.filter(user=user).exists()
    pending_request = ActivationRequest.objects.filter(user=user).exists()
    
    return render(request, 'accounts/profile.html', {
        'user': user, 
        'orders': orders, 
        'total_sell': total_sell, 
        'total_profit': total_profit, 
        'paid_profit': paid_profit, 
        'unpaid_profit': unpaid_profit,
        'can_request_payment': can_request_payment,
        'pending_request': pending_request,
    })

def signup(request):
    if request.method == "POST":

        name = request.POST['name'].strip()
        pass1 = ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))
        
        shopname = request.POST['shopname'].strip()
        email = request.POST['gmail'].strip() + '@gmail.com'
        phone = request.POST['phone'].strip()
        address = request.POST['address'].strip()

        try:
            validate_email(email)
        except ValidationError:
            messages.error(request, "Invalid gmail address.")
            return redirect('signup')
        
        username = ''.join([char for char in name if char.isalpha()])
        original_username = username
        while User.objects.filter(username=username).exists():
            username = original_username + str(random.randint(1000, 9999))
        
        # if User.objects.filter(email=email).exists():
        #     messages.error(request, "Email already registered!")
        #     return redirect('signup')

        user = User.objects.create_user(username=username, email=email, password=pass1)
        user.first_name = name
        user.shopname = shopname
        user.phone = phone
        user.address = address
        user.save()

        email_subject = "Confirmation Mail - bw.etrail.com.bd"
        template_name = 'accounts/mail_activation.html'
        send_email(user, request, user.email, email_subject, template_name, pass1)

        messages.success(request, "Please check your gmail.")
        return redirect('signin')

    return render(request, 'accounts/signup.html')

def signin(request):
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password = request.POST['password'].strip()
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('profile', username=username)
        else:
            messages.error(request, "Invalid username or password.")
    
    return render(request, 'accounts/signin.html')

def signout(request):
    logout(request)
    messages.error(request, "Sign out successfully.")
    return redirect('home')

def send_email(user, request, mail, email_subject, template_name, pass1):
    current_site = get_current_site(request)
    message = render_to_string(template_name, {
        'username': user.username,
        'pass': pass1,
        'domain': current_site.domain,
    })
    email = EmailMessage(email_subject, message, settings.EMAIL_HOST_USER, [mail],)
    email.fail_silently = True
    email.send()

@login_required
def update(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)

    if request.method == 'POST':

        shopname = request.POST.get('shopname').strip()
        name = request.POST.get('name').strip()
        phone = request.POST.get('phone').strip()
        address = request.POST.get('address').strip()

        user.shopname = shopname
        user.first_name = name
        user.phone = phone
        user.address = address
    
        user.save()
        messages.success(request, 'Your profile has been updated successfully.')
        return redirect('profile', user.username)

    return render(request, 'accounts/update.html', {'user': user})

def custom_404(request, exception):
    return render(request, 'accounts/404.html', {}, status=404)

templates/accounts/mail_activation.html
{% autoescape off %}
Welcome to Business with etrail

username: {{ username }}
password: {{ pass }}

Sign in: {{ domain }}/accounts/login/
{% endautoescape %}

templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="soash">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Profile</title>

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/profile.css' %}">
  
</head>
<body>

    <ul>
        <li><a class="active" href="{% url 'home' %}">Bw eTrail</a></li>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'signin' %}">Sign In</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'profile' user.username %}">Profile</a>
        </li>
        {% endif %}
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}">Policy</a></li>
    </ul>

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <strong>Message:</strong> {{ message }}
        </div>
    {% endfor %}

    <h1 style="text-align:center;">Profile</h1>
    
    <div class="center">
        <table class="profile">
            <tr>
                <td>Username</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>Shop Name</td>
                <td>{{ user.shopname }}</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>{{ user.first_name }}</td>
            </tr>
            <tr>
                <td>Gmail</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>bKash</td>
                <td>{{ user.phone }}</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <td>Activation Date</td>
                <td>{{ user.activation_date }}</td>
            </tr>
            <tr>
                <td>Expiry Date</td>
                <td>{{ user.expiry_date }}</td>
            </tr>
            <tr>
                <td>Total Sell</td>
                <td>{{ total_sell }} tk</td>
            </tr>
            <tr>
                <td>Paid Profit</td>
                <td>{{ paid_profit }} tk</td>
            </tr>
            <tr>
                <td>Unpaid Profit</td>
                <td>{{ unpaid_profit }} tk</td>
            </tr>
            <tr>
                <td>Account Status</td>
                <td>
                    {% if user.reseller_status == 'not_active' %}
                        {{ user.get_reseller_status_display }}

                        {% if pending_request %}
                            | Pending
                        {% else %}
                            <br><br><div>To active your account make <b>Payment</b> 1000tk in bKash. <br>
                            bKash Number: +8801580660031
                            or </div><span class="bkash-span"> <img src="https://i.ibb.co/VVCFZmw/bkash.png" class=bkash-logo> <a href="https://shop.bkash.com/etrailcombd01580660031/paymentlink" class="bkash">Click here to Pay</a>
                            </span>
                            <form method="POST" action="{% url 'requestA' %}" class="form">{% csrf_token %}
                                <div class="input-group">
                                    <span class="input-group-text">+88</span>
                                    <input type="text" name="phone" class="input-group-box" maxlength="11" required pattern="\d{11}" placeholder="Bkash number" title="Enter 11 digits for phone number">
                                </div>            
                                <input type="text" name="reference" placeholder="Reference" required>
                                <input type="number" name="amount" placeholder="Amount" min=0 required>
                                <input type="text" name="trxid" placeholder="TrxID" required>
                                <button type="submit">Activate</button>
                            </form>
                        {% endif %}
                    {% elif user.reseller_status == 'active' %}
                        {{ user.get_reseller_status_display }}
                    {% endif %}
                </td>
            </tr>
            

        </table>
        
        <div style="display: flex; flex-wrap: wrap; justify-content: center;">
        {% if request.user == user %}
            <a href="{% url 'signout' %}" class="button button-red" style="width: 120px;">Sign Out</a>
            <a href="{% url 'update' %}" class="button button-blue" style="width: 120px;">Update Profile</a>

            {% if can_request_payment %}
            <form method="post" action="{% url 'request_payment' %}" style="text-align: center;">{% csrf_token %}
                <button type="submit" class="button button-green" style="width: 190px;">Request Payment</button>
            </form>
            {% else %}
            <form style="text-align: center;">
                <button type="submit" class="button button-black" style="width: 190px;" disabled><del>Request Payment</del></button>
            </form>
            {% endif %}
        {% endif %}
            <a href="{% url 'user_payment_history' user.username %}" class="button button-gray" style="width: 120px;">Payment History</a>
        </div>
       
    </div>  

    <h1>Orders</h1>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Invoice No</th>
                    <th>Invoice Date</th>

                    <th>Reseller</th>
                    <th>Customer Name</th>
                    <th>Phone</th>
                    <th>Address</th>

                    <th>Product Name</th>
                    <th>Product Price</th>
                    <th>Sell Price</th>
                    <th>Quantity</th>
                    <th>Profit</th>
                    <th>Advance</th>
                    <th>Delivery Charge</th>
                    <th>bKash</th>
                    <th>Amount</th>
                    <th>TrxID</th>
                    <th>Reference</th>
                    <th>Cash on Delivery</th>

                    
                    <th>Profit Status</th>
                    <th>Order Status</th>
                    <th>Delivery Status</th>
                    <th>Invoice</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{ order.invoice_no }}</td>
                    <td>{{ order.invoice_date }}</td>

                    <td><a href="/accounts/{{ order.user }}">{{ order.user }}</a></td>
                    <td>{{ order.name }}</td>
                    <td>{{ order.phone }}</td>
                    <td>{{ order.address }}</td>
                    <td><a href="/category/{{ order.product.category.slug }}/{{ order.product.slug }}">{{ order.product_name }}</a></td>
                    
                    <td>{{ order.product_price }}</td>
                    <td>{{ order.sell_price }}</td>
                    <td>{{ order.quantity }}</td>
                    <td>{{ order.profit }}</td>
                    <td>{{ order.adv }}</td>
                    <td>{{ order.delivery_charge }}</td>
                    <td>{{ order.bKash }}</td>
                    <td>{{ order.amount }}</td>
                    <td>{{ order.trxid }}</td>
                    <td>{{ order.reference }}</td>
                    <td>{{ order.cod }}</td>
                
                    
                    
                    <td>{{ order.get_profit_status_display }}</td>
                    <td>{{ order.get_order_status_display }}</td>
                    <td>{{ order.get_delivery_status_display }}</td>
                    <td>
                        <a href="{% url 'generate_invoice_pdf' invoice_no=order.invoice_no %}"><i class="bi bi-download"></i></a>
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <footer>
        <span>&copy; 2024 | <a href="https://soash.github.io">Soash</a></span>
    </footer>

</body>
</html>

templates/accounts/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="soash">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/signup.css' %}">
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>

    <ul>
        <li><a class="active" href="{% url 'home' %}">Bw eTrail</a></li>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'signin' %}">Sign In</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'profile' user.username %}">Profile</a>
        </li>
        {% endif %}
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}">Policy</a></li>
    </ul>

    <h1 style="text-align:center;">Sign In</h1>
    
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <strong>Message:</strong> {{ message }}
        </div>
    {% endfor %}

    <form method="post" action="{% url 'signin' %}"> {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" maxlength="50" required pattern="[a-zA-Z0-9]+" title="Only letters, numbers are allowed">

        <label for="pass1">Password</label> 
        <input type="password" name="password" id="pass1" required>
        <span toggle="#pass1" class="bi bi-eye-slash toggle-icon toggle-password"></span>
    
        <button type="submit">Sign In</button>
    </form>

    <footer>
        <span>&copy; 2024 | <a href="https://soash.github.io">Soash</a></span>
    </footer>
  
    <script>
        $(document).ready(function() {
          $(".toggle-password").click(function() {
            $(this).toggleClass("bi-eye bi-eye-slash");
            var input = $($(this).attr("toggle"));
            input.attr("type", input.attr("type") === "password" ? "text" : "password");
          });
        }); 
    </script>

</body>
</html>

templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="soash">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/signup.css' %}"> 
    <link rel="stylesheet" href="{% static 'common.css' %}"> 
</head>
<body>

    <ul>
        <li><a class="active" href="{% url 'home' %}">Bw eTrail</a></li>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'signin' %}">Sign In</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'profile' user.username %}">Profile</a>
        </li>
        {% endif %}
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}">Policy</a></li>
    </ul>

    <h1 style="text-align:center;">Sign Up</h1>

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <strong>Message:</strong> {{ message }}
        </div>
    {% endfor %}

    <form method="post" action="{% url 'signup' %}" id="signupForm">{% csrf_token %}
        <label>Shop Name:</label>
        <input type="text" name="shopname" maxlength="50" required>

        <label>Full Name:</label>
        <input type="text" name="name" maxlength="50" required>

        <label>Address:</label>
        <input type="text" name="address" maxlength="150" required>
          
        <label>Gmail:</label>
        <div class="input-group">
            <input class="input-group-box" type="text" name="gmail" maxlength="50" required pattern="[a-zA-Z0-9.]+" title="Only letters, numbers, and fullstop are allowed">
            <span class="input-group-text">@gmail.com</span>
        </div> 
          
        <label>bKash Number:</label>
        <div class="input-group">
            <span class="input-group-text">+88</span>
            <input class="input-group-box" type="text" name="phone" maxlength="11" required pattern="\d{11}" title="11 digits for bKash number">
        </div>

        <button type="submit" id="signupButton">Register</button>
    </form>

    <footer>
        <span>&copy; 2024 | <a href="https://soash.github.io">Soash</a></span>
    </footer>

</body>
</html>

templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="soash">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/signup.css' %}"> 
    <link rel="stylesheet" href="{% static 'common.css' %}"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>

    <ul>
        <li><a class="active" href="{% url 'home' %}">Bw eTrail</a></li>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'signin' %}">Sign In</a></li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'profile' user.username %}">Profile</a>
            {% else %}
            <a href="#">Profile</a>
            {% endif %}
        </li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}">Policy</a></li>
    </ul>

    <h1 style="text-align:center;">Update</h1>

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <strong>Message:</strong> {{ message }}
        </div>
    {% endfor %}

    <form method="post" action="{% url 'update' %}"> {% csrf_token %}

        <label>Shop Name:</label>
        <input type="text" name="shopname" maxlength="50" value="{{ user.shopname }}" required>

        <label for="name">Name:</label>
        <input type="text" name="name" maxlength="50" value="{{ user.first_name }}" required>

        <label>Phone:</label>
        <div class="input-group">
            <span class="input-group-text">+88</span>
            <input class="input-group-box" type="text" name="phone" value="{{ user.phone }}" maxlength="11" pattern="\d{11}" title="11 digits for bKash number" required>
        </div>

        <label>Address:</label>
        <input type="text" name="address" value="{{ user.address }}" maxlength="150" required>

        <button type="submit">Update</button>
    </form>
    
    <footer>
        <span>&copy; 2024 | <a href="https://soash.github.io">Soash</a></span>
    </footer>

</body>
</html>